@base_url = http://localhost:8080
@resource_name = answers
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzU1ODcwMDAsInJvbGVzIjpbInVzZXIiXSwic3ViIjoyfQ.SwOP0beaeCPNg5cP_plMWVEb6nJxPYbBk2rM5sSGYF0

###

GET {{base_url}}/api/v1/users/me/{{resource_name}} HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{base_url}}/api/v1/users/me/{{resource_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "question_id": 3,
    "user_id": 1,
    "content": "{\"value\":123}"
}

###

GET {{base_url}}/api/v1/users/me/{{resource_name}}/1 HTTP/1.1
Authorization: Bearer {{token}}

###

PUT {{base_url}}/api/v1/users/me/{{resource_name}}/1 HTTP/1.1
Authorization: Bearer {{token}}

{
    "question_id": 2,
    "user_id": 1,
    "content": "foo bar"
}

###

DELETE {{base_url}}/api/v1/users/me/{{resource_name}}/10 HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}