@base_url = https://lekkoatletawka.pl
@resource_name = athletes
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDAzMzY0MjgsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MX0.YyoNHxaU00Pfwpl9wdyrdhuQljGBqew65uRiFXYod_0

###

GET {{base_url}}/api/v1/{{resource_name}}?search=kaczmarek HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{base_url}}/api/v1/{{resource_name}}/1 HTTP/1.1
Authorization: Bearer {{token}}