@base_url = http://localhost:8080
@resource_name = events
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzI5ODE3NDIsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MX0.KV_jnHhrvPtSFgL8GlTH30xKPUtcbryJmBnQlSQtlJU

###

GET {{base_url}}/api/healthz HTTP/1.1

###

GET {{base_url}}/api/readyz HTTP/1.1

### 
POST {{base_url}}/api/v1/register HTTP/1.1
content-type: application/json

{
    "email": "user40@gmail.com",
    "password": "user123"
}

###
POST {{base_url}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

###
POST {{base_url}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "user40@gmail.com",
    "password": "user123"
}