@base_url = https://lekkoatletawka.pl
@resource_name = events
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDAzMzY0MjgsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MX0.YyoNHxaU00Pfwpl9wdyrdhuQljGBqew65uRiFXYod_0

###

GET {{base_url}}/api/healthz HTTP/1.1

###

GET {{base_url}}/api/readyz HTTP/1.1

### 
POST {{base_url}}/api/v1/register HTTP/1.1
content-type: application/json

{
    "email": "user40@gmail.com",
    "password": "user123"
}

###
POST {{base_url}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "Filip.Juza.2000@gmail.com",
    "password": "Filip313213"
}

###
POST {{base_url}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "organizer2@gmail.com",
    "password": "organizer123"
}

###
POST {{base_url}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "user40@gmail.com",
    "password": "user123"
}