@base_url = http://localhost:8080
@resource_name = pokemons
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE5Nzk3MDIsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MX0.Ae9Pg5ZX0tyE2MrMp7sGc4Y81WochTgUxxXg0ZPNKjg

###

GET {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "pokemon_name": "Pikachu",
    "email": "123",
    "attack": "foo"
}

###

GET {{base_url}}/api/v1/{{resource_name}}/1 HTTP/1.1
Authorization: Bearer {{token}}

###

PUT {{base_url}}/api/v1/{{resource_name}}/1 HTTP/1.1
Authorization: Bearer {{token}}

{
    "pokemon_name": "Pikachu",
    "age": 12,
    "email": "foo.bar@gmail.com",
    "attack": "Ember"
}

###

DELETE {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}
