@base_url = http://localhost:8080
@resource_name = pokemons
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzMzMzEzMjYsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MX0.zjVy6iZn6taW_en-uGAZ2-Hdo86Luf0TjVv8zktvJQI

###

GET {{base_url}}/api/v1/pokemons HTTP/1.1
Authorization: Bearer {{token}}