@base_url = http://localhost:8080
@resource_name = humans


###

GET {{base_url}}/healthz HTTP/1.1

###

GET {{base_url}}/readyz HTTP/1.1

### 

GET {{base_url}}/api/v1/{{resource_name}} HTTP/1.1

### 

GET {{base_url}}/api/v1/{{resource_name}}/1 HTTP/1.1

###

POST {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
content-type: application/json

{
    "height": 2.12,
    "name": "Ben"
}

### 

PUT {{base_url}}/api/v1/{{resource_name}}/1 HTTP/1.1
content-type: application/json

{
    "pokemon_name": "Bulbasaur",
    "age": 30,
    "attack": "Ember",
    "email": "pika@gmail.com"
}

### 

DELETE {{base_url}}/api/v1/{{resource_name}}/1 HTTP/1.1
