@base_url = http://localhost:8080

POST {{base_url}}/personsAdvaced HTTP/1.1
content-type: application/json

{
    "name": "John",
    "age": 30,
    "address": {
        "street": "Main Street",
        "city": "Alabama"
    }
}

###

GET {{base_url}}/healthz HTTP/1.1

###

GET {{base_url}}/readyz HTTP/1.1