@base_url = http://localhost:8080
@resource_name = users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzMzMzEzMjYsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MX0.zjVy6iZn6taW_en-uGAZ2-Hdo86Luf0TjVv8zktvJQI

###

GET {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "email": "foobarbazz@gmail.com",
    "password": "foobarbaz",
    "roles": [
        {
            "id": 3,
            "name": "organizer"
        }
    ]
}

###

GET {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}

###

PUT {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}

{
    "email": "foobarbazzz@gmail.com",
    "password": "foobarbaz",
    "roles": [
        {
            "id": 2,
            "name": "user"
        }
    ]
}

###

DELETE {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}
