@base_url = http://localhost:8080
@resource_name = users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA2NTIzNjEsInJvbGVzIjpbImFkbWluIl0sInN1YiI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.OEYUCEBsMVIhcpKJ19C1otn049x676C8FCsmTvcN9Dc

###

GET {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{base_url}}/api/v1/{{resource_name}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "email": "organizer2@gmail.com",
    "password": "organizer123",
    "roles": [
        {
            "id": 3,
            "name": "organizer"
        },
        {
            "id": 2,
            "name": "user"
        }
    ]
}

###

GET {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}

###

PUT {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}

{
    "email": "foobarbazzz@gmail.com",
    "password": "foobarbaz",
    "roles": [
        {
            "id": 2,
            "name": "user"
        }
    ]
}

###

DELETE {{base_url}}/api/v1/{{resource_name}}/2 HTTP/1.1
Authorization: Bearer {{token}}
