- name: Build and deploy app
  hosts: lekkoatletawka
  become: yes
  vars_files:
  - files/secrets.yml
  - files/vars.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ golang_install_dir }}/go/bin"
  tasks:
    - name: create directory for source code
      ansible.builtin.file:
        path: "{{ source_code_dir }}"
        state: directory
      args:
        force: true

    - name: fetch source code
      ansible.builtin.git:
        repo: "https://github.com/filipio/athletics-backend.git"
        dest: "{{ source_code_dir }}"

    - name: build app
      ansible.builtin.command:
        cmd: "go build -o {{ service_bin_file }} ./cmd"
      args:
        chdir: "{{ source_code_dir }}"

    - name: migrate database
      ansible.builtin.command:
        cmd: "atlas migrate apply -u postgres://{{ db_user }}:{{ db_password }}@localhost:5432/{{ db_name }}?sslmode=disable"
      register: migrate_output
      args:
        chdir: "{{ source_code_dir }}"

    - name: show migration output
      ansible.builtin.debug:
        msg: "{{ migrate_output.stdout }}"
    
    - name: restart service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted


